SUBPROJECTS =	bmptranslator \
				pngtranslator

#				jpg2000translator \
#				jpgtranslator \
#				libtifftranslator \
#				ppmtranslator \
#				sgitranslator \
#				stxttranslator \
#				tgatranslator \
#				tifftranslator

include ../../../Makefile.common

